name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  deny:
    name: Deny
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Install lld
        run: sudo apt-get update && sudo apt-get install -y lld wget unzip
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - uses: actions/checkout@v2
      - name: Fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --all-features --tests --benches --examples
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all --all-features --tests --benches --examples -- -D warnings
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Install lld
        run: sudo apt-get update && sudo apt-get install -y lld wget unzip
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions/checkout@v2
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-features
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Install lld
      run: sudo apt-get update && sudo apt-get install -y lld wget unzip
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - uses: actions/checkout@v2
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features --all-targets
  benches:
    name: Benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Install lld
        run: sudo apt-get update && sudo apt-get install -y lld wget unzip
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions/checkout@v2
      - name: Bench
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --all --features=unstable